### ISSUE TITLE
downloadTemplate is only downloading part of the repository

### ISSUE THREAD

**Issue by si-fab** [bluwy/giget-core#1]
`downloadTemplate` is failing to download all folders inside my project: I have this folder structure:

```
test_folder/
    test/
    test-a/
    test-b/
```

running downloadTemplate downloads:

```
test_folder/
    test-a/
```

The folders `test` and `test-b` are missing. 
Here is a reproduce of the issue: https://github.com/si-fab/reproduce-giget-core-bug 

Inside this repository execute this steps to reproduce the bug:
- `npm install`
- `node .`
- `ls test-download/test_folder/` => should print `test`, `test-a`, `test-b`. In my case it prints `test-a` only.

My system:
macOS 15.0.1
Node v22

**Comment by bluwy** [comment]
The repo doesn't seem to have `test` or `test-b` to download from. Could you push them up so that when I download locally I can check if it downloaded them>

**Comment by si-fab** [comment]
indeed I haven't uploaded them 🙈. Now my reproduction is not able to reproduce the issue anymore. I will try to improve it and come back to you as soon as possible.
I have a similar issue on our project (where the files are uploaded to github 😅) . Astro-create stopped working for us with the change to @bluwy/giget-core. So I would be happy if I can reproduce it.

**Comment by si-fab** [comment]
Thank you! This is the problem with my project:
when I run `await downloadTemplate('gh:LightNetDev/lightnet-library/examples/sk8-ministries')` it will only download part of what is inside `src/content/`. For me `media-collections` and `media` folder are missing. Do you see the same behaviour on your machine?

**Comment by bluwy** [comment]
Yeah I can see the same. Looks like it's not correctly writing some files when unzipping. I'll make and release a fix.

**Comment by bluwy** [comment]
Looks like unzipping directories is harder than I thought. I'll have to investigate further tomorrow and probably use a better library to unzip the templates.

**Comment by si-fab** [comment]
Cool, that you found the cause 👍. Let me know if I can help you with fixing the issue.

**Comment by bluwy** [comment]
It should be fixed now. I used back the `tar` library that was used in `giget` before so the behaviour should be the same. There's a lot of edge cases with writing parsed tar files to the file system that it's worth using a proper library instead.

**Comment by si-fab** [comment]
I can confirm: this fixed the bug ✅. Thank you for your work!
